gsc-tool.exe comp t6 "Player Raws/plant.gsc"
gsc-tool.exe comp t6 "Player Raws/zi0.gsc"
gsc-tool.exe comp t6 "Player Raws/tonestone.gsc"
gsc-tool.exe comp t6 "Player Raws/tek.gsc"
gsc-tool.exe comp t6 "Player Raws/shadez.gsc"
gsc-tool.exe comp t6 "Player Raws/yojurt.gsc"
gsc-tool.exe comp t6 "Player Raws/vistek.gsc"
gsc-tool.exe comp t6 "Player Raws/zeta.gsc"
gsc-tool.exe comp t6 "Player Raws/plugins/frfix_hud_override_zeta.gsc"
pause